// <auto-generated />
using System;
using DotNet7_MoonTechnoLab.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNet7_MoonTechnoLab.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230703071455_payreg")]
    partial class payreg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNet7_MoonTechnoLab.Model.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DotNet7_MoonTechnoLab.Model.PayReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ADJUSTMENTS")
                        .HasColumnType("double precision");

                    b.Property<string>("ATTDEDUCTION")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BANKACCT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BANKNAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BASICSALARY")
                        .HasColumnType("double precision");

                    b.Property<string>("COMMENTFIELD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("COSTCENTER")
                        .HasColumnType("integer");

                    b.Property<string>("CURRENCY")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DAILYRATE")
                        .HasColumnType("double precision");

                    b.Property<string>("DATEEMPLOYED")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DATETERMINATED")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DEDUCTIONS")
                        .HasColumnType("double precision");

                    b.Property<int>("EMPLOYEEID")
                        .HasColumnType("integer");

                    b.Property<double>("EMPLOYEEMCR")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYEEPAGIBIG")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYEESSS")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYEREC")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYERMCR")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYERPAGIBIG")
                        .HasColumnType("double precision");

                    b.Property<double>("EMPLOYERSSS")
                        .HasColumnType("double precision");

                    b.Property<string>("ERRORFIELD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EXCHANGERATE")
                        .HasColumnType("integer");

                    b.Property<string>("FILESTATUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FROM")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("GROSSINCOME")
                        .HasColumnType("double precision");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LOANPAYMENTS")
                        .HasColumnType("double precision");

                    b.Property<double>("MONTHLYALLOW")
                        .HasColumnType("double precision");

                    b.Property<double>("MONTHLYSALARYRATE")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDBASIC")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDGROSS")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDMCREMPLOYEE")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDMCREMPLOYER")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDNTX")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDPAGIBIGEMPLOYEE")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDPAGIBIGEMPLOYER")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDSSSEMPLOYEE")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDSSSEMPLOYER")
                        .HasColumnType("double precision");

                    b.Property<double>("MTDWHTAX")
                        .HasColumnType("double precision");

                    b.Property<double>("NETSALARY")
                        .HasColumnType("double precision");

                    b.Property<double>("NETSALARYAFTERTAX")
                        .HasColumnType("double precision");

                    b.Property<double>("OTHERNTXINCOME")
                        .HasColumnType("double precision");

                    b.Property<double>("OTHERTXINCOME")
                        .HasColumnType("double precision");

                    b.Property<double>("OVERTIME")
                        .HasColumnType("double precision");

                    b.Property<string>("PAYCODE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PAYDATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PAYMENTFREQ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PAYMENTTYPE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PAYROLL")
                        .HasColumnType("integer");

                    b.Property<double>("PAYROLLCOST")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDBON13THNT")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDBON13THTX")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDGROSS")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDMCR")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDPAGIBIG")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDSSS")
                        .HasColumnType("double precision");

                    b.Property<double>("PREVIOUSYTDWITHOLDING")
                        .HasColumnType("double precision");

                    b.Property<double>("SALARYRATETYPE")
                        .HasColumnType("double precision");

                    b.Property<double>("TAXABLEINCOME")
                        .HasColumnType("double precision");

                    b.Property<string>("TAXSTATUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TAXTABLE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WITHOLDINGTAX")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("PayReg");
                });

            modelBuilder.Entity("DotNet7_MoonTechnoLab.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNet7_MoonTechnoLab.Model.User", b =>
                {
                    b.HasOne("DotNet7_MoonTechnoLab.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
